'use client';

import Link from 'next/link';
import { ArrowRight, Camera, FileCheck2, HeartHandshake, Upload } from 'lucide-react';
import { useLanguage } from '../../components/LanguageProvider';

export default function Contribute() {
  const { copy } = useLanguage();
  return <main className="mx-auto max-w-6xl px-5 pb-28 pt-32 md:pt-40"><div className="grid items-center gap-12 md:grid-cols-[1fr_.8fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-green-600">{copy.nav.contribute}</p><h1 className="mt-4 text-5xl font-bold leading-[1.04] tracking-tight text-green-950 md:text-7xl">Help make local transport easier to find.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-green-950/65">A timetable photographed at a bus stop can become structured information for the next person waiting there.</p><Link href="/upload" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-full bg-green-700 px-6 font-bold text-white shadow-lg shadow-green-900/15"><Camera size={18}/> {copy.home.upload}<ArrowRight size={17}/></Link></div><div className="surface relative overflow-hidden p-8"><div className="absolute -right-10 -top-10 h-32 w-32 rounded-full bg-yellow-200"/><HeartHandshake className="relative text-green-700" size={34}/><h2 className="relative mt-6 text-2xl font-bold text-green-950">Every contribution stays accountable.</h2><div className="relative mt-7 space-y-4">{[['Capture', 'Upload a clear source document.'], ['Review', 'Correct uncertain extracted values.'], ['Share', 'Verified data can help other riders.']].map(([title, text], index) => <div key={title} className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-green-100 text-sm font-bold text-green-700">{index + 1}</span><div><p className="font-bold text-green-950">{title}</p><p className="text-sm text-green-950/60">{text}</p></div></div>)}</div></div></div><section className="mt-20 grid gap-4 border-t border-green-100 pt-10 sm:grid-cols-3"><div><Upload className="text-green-700" size={22}/><h2 className="mt-4 font-bold text-green-950">Image or PDF</h2><p className="mt-1 text-sm text-green-950/60">Use the document you already have.</p></div><div><FileCheck2 className="text-green-700" size={22}/><h2 className="mt-4 font-bold text-green-950">Confidence-aware</h2><p className="mt-1 text-sm text-green-950/60">Uncertain fields stay visible for review.</p></div><div><HeartHandshake className="text-green-700" size={22}/><h2 className="mt-4 font-bold text-green-950">Built together</h2><p className="mt-1 text-sm text-green-950/60">Local knowledge improves local routes.</p></div></section></main>;
}
