'use client';

import Link from 'next/link';
import { ArrowRight, Check, FileText, MapPinned, ScanLine, ShieldCheck, Sparkles, Upload } from 'lucide-react';
import { useLanguage } from '../components/LanguageProvider';
import PublicMapExplorer from '../components/PublicMapExplorer';

export default function Home() {
  const { copy } = useLanguage();
  return <main className="overflow-hidden pb-24 md:pb-10">
    <section className="mx-auto grid max-w-6xl items-center gap-12 px-5 pb-20 pt-32 md:grid-cols-[1.05fr_.95fr] md:pb-28 md:pt-44">
      <div className="rise">
        <div className="inline-flex items-center gap-2 rounded-full border border-yellow-200 bg-yellow-50 px-3 py-2 text-xs font-bold uppercase tracking-[.14em] text-green-900"><Sparkles size={14} className="text-yellow-600"/>{copy.home.eyebrow}</div>
        <h1 className="mt-6 max-w-3xl text-5xl font-bold leading-[1.02] tracking-[-.04em] text-green-950 md:text-7xl">{copy.home.title}</h1>
        <p className="mt-6 max-w-xl text-lg leading-8 text-green-950/65">{copy.home.description}</p>
        <div className="mt-9 flex flex-wrap gap-3"><Link href="/upload" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-green-700 px-6 font-bold text-white shadow-lg shadow-green-900/15 transition hover:-translate-y-0.5 hover:bg-green-800"><Upload size={18}/>{copy.home.upload}<ArrowRight size={16}/></Link><Link href="/map" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-green-200 bg-white px-6 font-bold text-green-800 transition hover:bg-green-50"><MapPinned size={18}/>{copy.home.explore}</Link></div>
        <div className="mt-8 flex items-center gap-3 text-sm text-green-900/60"><span className="grid h-7 w-7 place-items-center rounded-full bg-yellow-300 text-green-950"><Check size={15}/></span> Human-checked before public discovery</div>
      </div>
      <div className="relative min-h-[410px] overflow-hidden rounded-[32px] border border-green-100 bg-[#f0f9f1] p-6 shadow-[0_28px_70px_rgba(21,128,61,.12)] md:min-h-[510px]">
        <div className="soft-grid absolute inset-0 opacity-70"/><div className="absolute -right-14 -top-14 h-48 w-48 rounded-full bg-yellow-300/75"/><div className="absolute bottom-0 left-0 h-44 w-44 rounded-full bg-green-200/70"/>
        <div className="relative flex h-full flex-col justify-between"><div className="flex justify-between text-xs font-bold uppercase tracking-[.18em] text-green-800"><span>Paper</span><span>Transit data</span></div><div className="relative mx-auto w-full max-w-[380px] rotate-[-4deg] rounded-2xl border border-green-100 bg-white p-6 shadow-xl"><div className="flex items-start justify-between"><div><div className="h-2 w-28 rounded bg-green-200"/><div className="mt-3 h-4 w-44 rounded bg-green-800"/></div><FileText className="text-yellow-500" size={25}/></div><div className="mt-8 space-y-4">{[['Thrissur','06:15'],['Mannuthy','06:28'],['Angamaly','07:20'],['Aluva','07:40']].map(([stop,time], index)=><div key={stop} className="flex items-center gap-3"><span className="grid h-6 w-6 place-items-center rounded-full bg-green-100 text-xs font-bold text-green-800">{index+1}</span><span className="flex-1 border-b border-dashed border-green-200 pb-2 text-sm font-semibold">{stop}</span><span className="rounded-lg bg-yellow-50 px-2 py-1 text-sm font-bold text-green-900">{time}</span></div>)}</div></div><div className="relative mx-auto flex w-full max-w-[400px] items-center justify-between rounded-2xl border border-green-200 bg-green-800 p-4 text-white shadow-xl"><div><p className="text-[10px] uppercase tracking-[.18em] text-green-200">Verified route</p><p className="mt-1 text-lg font-bold">Thrissur → Ernakulam</p></div><ScanLine className="text-yellow-300" size={30}/></div></div>
      </div>
    </section>
    <PublicMapExplorer />
    <section className="border-y border-green-100 bg-white"><div className="mx-auto max-w-6xl px-5 py-20"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-green-600">{copy.home.howTitle}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-green-950 md:text-5xl">{copy.home.howDescription}</h2></div><div className="mt-12 grid gap-4 md:grid-cols-4">{copy.home.steps.map(([number,title,description], index) => <article key={number} className={`rise delay-${index} rounded-3xl border border-green-100 bg-[#fbfefb] p-6`}><span className="text-sm font-bold text-yellow-600">{number}</span><div className="mt-10 grid h-10 w-10 place-items-center rounded-xl bg-green-100 text-green-700">{index === 0 ? <FileText size={19}/> : index === 1 ? <ScanLine size={19}/> : index === 2 ? <ShieldCheck size={19}/> : <MapPinned size={19}/>}</div><h3 className="mt-5 text-xl font-bold text-green-950">{title}</h3><p className="mt-2 text-sm leading-6 text-green-950/60">{description}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-6xl gap-5 px-5 py-20 md:grid-cols-[1.2fr_.8fr]"><div className="rounded-[28px] bg-green-800 p-8 text-white md:p-10"><p className="text-sm font-bold uppercase tracking-[.18em] text-yellow-300">{copy.home.sample}</p><div className="mt-10 grid gap-3 md:grid-cols-[.8fr_1fr] md:items-center"><div className="rounded-2xl bg-white/10 p-5"><p className="text-xs uppercase tracking-wider text-green-200">Source image</p><div className="mt-5 space-y-3 opacity-80"><div className="h-2 w-32 rounded bg-green-200"/><div className="h-2 w-48 rounded bg-green-200"/><div className="h-2 w-40 rounded bg-yellow-300"/><div className="h-2 w-52 rounded bg-green-200"/></div></div><div className="rounded-2xl bg-white p-5 text-green-950"><p className="text-xs uppercase tracking-wider text-green-600">Structured result</p><p className="mt-4 font-bold">Angamaly <span className="float-right">07:20</span></p><div className="mt-4 route-line h-1 rounded-full"/><p className="mt-4 text-sm text-green-950/60">{copy.home.sampleText}</p></div></div></div><div className="surface p-8"><ShieldCheck className="text-green-700" size={28}/><h2 className="mt-5 text-2xl font-bold text-green-950">Built for trustworthy transit data.</h2><ul className="mt-6 space-y-4">{copy.home.trust.map(item => <li key={item} className="flex items-center gap-3 text-sm font-semibold text-green-950/70"><Check size={17} className="text-green-600"/>{item}</li>)}</ul></div></section>
  </main>;
}
