'use client';

import Link from 'next/link';
import { ArrowRight, LockKeyhole, UserRound } from 'lucide-react';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../../components/AuthProvider';

const api = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

export default function Login() {
  const router = useRouter(); const { setSession } = useAuth(); const [mode, setMode] = useState<'login' | 'signup'>('login'); const [form, setForm] = useState({ username: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); const response = await fetch(`${api}/auth/${mode === 'login' ? 'login' : 'signup'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) setError(data.detail || 'Could not complete authentication.'); else if (data.data?.token) { setSession(data.data.token, data.data.user); router.push('/profile'); } else setError(data.data?.message || 'Check your email to continue.'); setBusy(false); };
  return <main className="mx-auto max-w-md px-5 pb-28 pt-32 md:pt-44"><div className="surface p-7 md:p-9"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-green-700 text-white"><UserRound size={23}/></div><h1 className="mt-6 text-3xl font-bold text-green-950">{mode === 'login' ? 'Welcome back' : 'Create your TransitLens account'}</h1><p className="mt-2 text-sm leading-6 text-green-950/60">Your account keeps your uploads, corrections, and contributions connected to your username.</p><form onSubmit={submit} className="mt-7 space-y-4">{mode === 'signup' && <label className="block text-sm font-bold">Username<input required value={form.username} onChange={event => setForm({ ...form, username: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-green-100 px-4 outline-none focus:border-green-500" placeholder="tharun"/></label>}<label className="block text-sm font-bold">Email<input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-green-100 px-4 outline-none focus:border-green-500" placeholder="you@example.com"/></label><label className="block text-sm font-bold">Password<input required minLength={8} type="password" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-green-100 px-4 outline-none focus:border-green-500" placeholder="8 characters minimum"/></label>{error && <p className="rounded-xl bg-yellow-50 p-3 text-sm font-semibold text-green-950">{error}</p>}<button disabled={busy} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-green-700 font-bold text-white disabled:opacity-50">{busy ? 'Please wait...' : mode === 'login' ? 'Sign in' : 'Create account'}<ArrowRight size={17}/></button></form><button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')} className="mt-6 w-full text-center text-sm font-bold text-green-700">{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button><p className="mt-5 flex items-center justify-center gap-2 text-xs text-green-950/45"><LockKeyhole size={14}/> Passwords are never shown in the frontend.</p></div><p className="mt-5 text-center text-sm text-green-950/55">Public map browsing remains available without signing in.</p></main>;
}
