'use client';

import { Bell, Check, Clock3, Info, MapPin, Play, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import { useLanguage } from '../../components/LanguageProvider';

const api = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

export default function Alerts() {
  const { copy } = useLanguage();
  const [message, setMessage] = useState('');
  const [enabled, setEnabled] = useState(false);
  const trigger = async () => { const response = await fetch(`${api}/notifications/demo-trigger`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ stop_id: '2', advance_minutes: 5 }) }); const data = await response.json(); setMessage(data.message || 'A scheduled alert was triggered.'); };
  return <main className="mx-auto max-w-5xl px-5 pb-28 pt-32 md:pt-40"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-green-600">{copy.nav.alerts}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-green-950 md:text-6xl">{copy.alerts.title}</h1><p className="mt-4 text-lg text-green-950/60">{copy.alerts.subtitle}</p></div><div className="mt-10 grid gap-6 md:grid-cols-[1fr_.82fr]"><section className="surface p-7 md:p-9"><div className="flex items-start justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-yellow-100 px-3 py-1 text-xs font-bold text-green-950"><span className="h-2 w-2 animate-pulse rounded-full bg-yellow-600"/>{copy.alerts.demo}</div><h2 className="mt-6 text-2xl font-bold text-green-950">Mannuthy → Ernakulam</h2><p className="mt-2 text-sm text-green-950/60">{copy.alerts.notify}</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-green-100 text-green-700"><Bell size={23}/></div></div><div className="mt-8 space-y-3"><div className="flex items-center gap-3 rounded-2xl border border-green-100 p-4"><MapPin className="text-green-700" size={19}/><div><p className="text-xs text-green-950/50">Stop</p><p className="font-bold">Mannuthy · മണ്ണുത്തി</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-green-100 p-4"><Clock3 className="text-green-700" size={19}/><div><p className="text-xs text-green-950/50">Scheduled arrival</p><p className="font-bold">07:20 · 5 minutes before</p></div></div></div><button onClick={() => setEnabled(!enabled)} className={`mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full font-bold transition ${enabled ? 'bg-green-100 text-green-800' : 'bg-green-700 text-white hover:bg-green-800'}`}>{enabled ? <><Check size={18}/> Alert enabled</> : <><Bell size={18}/> Create alert</>}</button></section><aside className="space-y-5"><section className="rounded-3xl bg-green-800 p-7 text-white"><ShieldAlert className="text-yellow-300" size={24}/><h2 className="mt-5 text-xl font-bold">A clear promise.</h2><p className="mt-2 text-sm leading-6 text-green-100">{copy.alerts.note}</p></section><section className="surface p-7"><div className="flex gap-3"><Info className="shrink-0 text-green-600" size={20}/><div><h2 className="font-bold text-green-950">Try the demo clock</h2><p className="mt-1 text-sm leading-6 text-green-950/60">See what a timetable-based reminder feels like without waiting for the real time.</p></div></div><button onClick={trigger} className="mt-6 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full border border-green-200 font-bold text-green-800 hover:bg-green-50"><Play size={16}/>{copy.alerts.trigger}</button>{message && <div className="mt-4 rounded-2xl bg-yellow-50 p-4 text-sm font-semibold text-green-950">{message}</div>}</section></aside></div></main>;
}
